# Movie

LOAD DATA LOCAL INFILE '~/data/movie.del' INTO TABLE Movie
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# Actor

LOAD DATA LOCAL INFILE '~/data/actor1.del' INTO TABLE Actor
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/actor2.del' INTO TABLE Actor
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/actor3.del' INTO TABLE Actor
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# Sales

LOAD DATA LOCAL INFILE '~/data/sales.del' INTO TABLE Sales
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# Director

LOAD DATA LOCAL INFILE '~/data/director.del' INTO TABLE Director
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# MovieGenre

LOAD DATA LOCAL INFILE '~/data/moviegenre.del' INTO TABLE MovieGenre
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# MovieDirector

LOAD DATA LOCAL INFILE '~/data/moviedirector.del' INTO TABLE MovieDirector
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# MovieActor

LOAD DATA LOCAL INFILE '~/data/movieactor1.del' INTO TABLE MovieActor
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/movieactor2.del' INTO TABLE MovieActor
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# MovieRating

LOAD DATA LOCAL INFILE '~/data/movierating.del' INTO TABLE MovieRating
	FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';


# Review


# MaxPersonID

INSERT INTO MaxPersonID VALUES(69000);


# MaxMovieID

INSERT INTO MaxMovieID VALUES(4750);
